spring:
  application:
    name: client-service
  datasource:
    url: jdbc:mysql://localhost:3306/client_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
app:
  jwt:
    secret: "MaSuperCleTresSecretePourJWT1234567890"
    expiration: 3600000
