spring:
  datasource:
    url: jdbc:mysql://localhost:3306/immobilier_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mes-config-ms:
  biens-last: 10
